//2020-12-08 MRP SEARCH MRP 강동욱 ==============================================================
export const SEARCH_MPS_LIST_REQUEST = 'src/ERP/LOGISTIC/Saga/SEARCH_MPS';
export const SEARCH_MPS_LIST_SUCCESS = 'src/ERP/LOGISTIC/Saga/SEARCH_MPS_SUCCESS';
export const SEARCH_MRP_LIST_REQUEST = 'src/ERP/LOGISTIC/Saga/SEARCH_MRP';
export const SEARCH_MRP_LIST_SUCCESS = 'src/ERP/LOGISTIC/Saga/SEARCH_MRP_SUCCESS';
export const INSERT_MRP_LIST_REQUEST = 'src/ERP/LOGISTIC/Saga/INSERT_MRP_LIST';

export const SEARCH_MRP_GETMRPLIST_REQUEST = 'src/ERP/LOGISTIC/Saga/SEARCH_MRP_GETMRPLIST';
export const SEARCH_MRP_GETMRPLIST_SUCCESS =
    'src/ERP/LOGISTIC/Saga/SEARCH_MRP_GETMRPLIST_SUCCESS';

export const SEARCH_GATHER_LIST_SAGA = 'src/ERP/LOGISTIC/Saga/SEARCH_GATHER_LIST';
export const SEARCH_GATHER_LIST_SUCCESS = 'src/ERP/LOGISTIC/Saga/SEARCH_GATHER_LIST_SUCCESS';

export const INSERT_GATHER_LIST_REQUEST = 'src/ERP/LOGISTIC/Saga/INSERT_GATHER_LIST';
//2020-12-08 MRP SEARCH MRP 강동욱 종료 =========================================================
